spring:
  datasource:
    url: jdbc:mysql://192.168.3.169:3306/cache
    username: root
    password: 123456
  redis:
    host: 192.168.3.169
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    pers:
      guzx:
        springbootcache:
          mapper: debug

#debug: true